// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMou4FBBpPWAOUGiyVRuG6e1cmZ9aJ8lc',
    appId: '1:945355047774:web:eb5673038a96897dc3c5cf',
    messagingSenderId: '945355047774',
    projectId: 'email-8fb24',
    authDomain: 'email-8fb24.firebaseapp.com',
    storageBucket: 'email-8fb24.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlo9HJK-cVw2QY0L7JltxRHgQWBCB0uYA',
    appId: '1:945355047774:android:f8a55888da5c15d3c3c5cf',
    messagingSenderId: '945355047774',
    projectId: 'email-8fb24',
    storageBucket: 'email-8fb24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4of1HC4Bnau0D8DjEYhCRjw4rAp-DT8U',
    appId: '1:945355047774:ios:4f07c0454aa97869c3c5cf',
    messagingSenderId: '945355047774',
    projectId: 'email-8fb24',
    storageBucket: 'email-8fb24.appspot.com',
    iosClientId: '945355047774-8nh6monk1ug6a5kp85bshhg29l7ghkfj.apps.googleusercontent.com',
    iosBundleId: 'com.example.emailDetection',
  );
}
